<a href="https://colab.research.google.com/github/MFaiqKhan/classical_MachineLearning/blob/main/k_Fold_Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Which is Model is better for the same dataset? Cross validation is the technique to answer that question.

Cross-Validation can be performed as:

Option 1: 
Use All available data for training and test on same dataset(Using 100% to train model and train model)

Option 2: Split dataset for training and testing( train_test_split method )

Above option ain't that good thats why we use K-fold validation

K_fold : divide dataset samples into folds, 100 samples divided in 5 folds where 4 will be used for train and one will be used for test one by one .
then we will average the model score. 

K-fold cross-validation is a technique used to evaluate the performance of a machine learning model. It involves splitting the data into K equal parts or "folds" and training the model K times. In each iteration, one of the folds is used as the validation set and the remaining K-1 folds are used for training. The process is repeated K times, with each of the K folds used exactly once for validation.

The results of each fold are then averaged to obtain a single estimate of the model's performance. K-fold cross-validation helps to mitigate the issue of overfitting by using different training and validation sets in each iteration, ensuring that the model is evaluated on a variety of data.

Common values for K include 5, 10, and 20, but the appropriate value will depend on the size of the dataset and the computational resources available. A larger value of K will result in a more accurate estimate of the model's performance, but it will also increase the computational time.



In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.3)



Here the sample distribution in splits are not uniform , means they will change again if we run the above code again.
If I run the code above multiple times it will give me different results with variation in score accuracy .

In [3]:
lr = LogisticRegression(multi_class='ovr', max_iter=1000)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)


0.9555555555555556

In [4]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test,y_test)

0.987037037037037

In [5]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test,y_test)

0.975925925925926

Using K-fold,

We set shuffle=True to shuffle the data before splitting

The random_state parameter in the KFold method of scikit-learn is used to set the random seed used by the random number generator for shuffling the data samples. It is an optional parameter and if not specified, it will use a different random seed each time it is called.

Setting the random_state parameter to a fixed value ensures that the same samples are selected for each fold when the KFold method is called again with the same parameters. This is useful for reproducibility purposes and allows for the results to be compared across multiple runs.

For example, if you set random_state=42 when creating a KFold object, it will always generate the same sequence of random numbers for shuffling the data samples, and hence, will produce the same folds for cross-validation every time it is called with the same parameters.

In [6]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3) # means sample is divide into 3 folds, one is for validation other two for training
kf

KFold(n_splits=3, random_state=None, shuffle=False)

The method kf.split([1,2,3,4,5,6,7,8,9]) is used to generate the indices for splitting the data [1,2,3,4,5,6,7,8,9] into training and testing sets using the KFold cross-validation with the number of folds specified when creating the KFold object.

The resulting train_index and test_index variables in the example will contain the indices of the data points for the current fold.

In [7]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print("Train Index:", train_index, ", Test Index:", test_index) # gets me the index for datapoints of 3 folds of training and test samples in each fold.

Train Index: [3 4 5 6 7 8] , Test Index: [0 1 2]
Train Index: [0 1 2 6 7 8] , Test Index: [3 4 5]
Train Index: [0 1 2 3 4 5] , Test Index: [6 7 8]


The output of the code shows the indices of the training and test sets for each fold generated by the KFold cross-validation method.

In each iteration of the for loop, the code prints the indices of the training and test sets for the current fold. The output is as follows:

In the first iteration, the training set includes the samples with indices 3, 4, 5, 6, 7, and 8, while the test set includes the samples with indices 0, 1, and 2.
In the second iteration, the training set includes the samples with indices 0, 1, 2, 6, 7, and 8, while the test set includes the samples with indices 3, 4, and 5.
In the third iteration, the training set includes the samples with indices 0, 1, 2, 3, 4, and 5, while the test set includes the samples with indices 6, 7, and 8.
In summary, the KFold method is splitting the data into 3 folds, and each fold is used once as a test set while the remaining folds are used as training sets. By shuffling the data and specifying a random state, the KFold method ensures that the data is randomly split into the folds for cross-validation.






In [9]:
def get_score(model, X_train, X_test, y_train, y_test):
  model.fit(X_train, y_train)
  return model.score(X_test, y_test)

The function first fits the model to the training data using the model.fit() method, which trains the model on the input data. It then computes the accuracy score of the model on the testing data using the model.score() method, which returns the mean accuracy on the given test data and labels.

Finally, the function returns the accuracy score obtained by the model on the testing data. This function can be useful when we want to evaluate different machine learning models on the same dataset using k-fold cross-validation or any other evaluation method.

In [10]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.987037037037037

There are several types of k-folds:

- KFold: This is the basic K-fold cross-validation. In this, the data is split into K folds, and each fold is used as a testing set at some point.

- StratifiedKFold: This K-fold cross-validation is suitable for classification problems. Each fold is made by preserving the percentage of samples for each class.

- TimeSeriesSplit: This K-fold cross-validation is suitable for time-series data. In this, the data is split in such a way that each fold contains data from earlier time points than the previous fold.
 
- GroupKFold: This K-fold cross-validation is suitable for when the data contains groups. In this, the data is split in such a way that the same group does not appear in two different folds.

Stratified K-Fold: Stratified K-Fold cross-validation is a modification of KFold. The main difference between these two is that in Stratified K-Fold, we divide the data into folds, so that each fold has the same proportion of target values as the complete dataset. This method helps in obtaining better results for classification tasks. Stratification is the process of rearranging the data so as to ensure that each fold is a good representative of the whole. For example, in a binary classification problem, each fold should have approximately the same percentage of samples of each target class as the complete dataset.

stratifiedKFold divides classification in uniform manner, 
e.g: types of number of flowers in one fold and other fold should be same.

this means that each fold contains roughly the same proportions of the two types of class labels.

In [14]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits = 3)
folds

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [ ]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data, digits.target):
  #print("Train Index:", train_index, ", Test Index:", test_index)
  # loop over the splits and fit a model on each fold
    X_train, X_test = digits.data[train_index], digits.data[test_index]
    y_train, y_test = digits.target[train_index], digits.target[test_index]

    scores_l.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

The above code is performing K-fold cross-validation for classification on the digits dataset using Logistic Regression, Support Vector Machine (SVM), and Random Forest Classifier models.

Here's how it works:

- Three empty lists, scores_l, scores_svm, and scores_rf, are created to store the accuracy scores of each fold for each model.

- The KFold iterator is instantiated with 3 folds using kf.split(digits.data, digits.target). It returns the indices of the data for each train-test split.
- For each split, X_train, X_test, y_train, and y_test are obtained from the indices returned by the KFold iterator.
- The get_score() function is called for each model, passing the training and testing data for the current split. The function fits the model on the training data and returns the accuracy score on the testing data.
- The accuracy score for each model is appended to the corresponding list.
- After all the splits have been processed, the scores_l, scores_svm, and scores_rf lists contain the accuracy scores for each model for each fold.

The accuracy scores can then be used to compare the performance of the three models and determine which one works best for the given classification problem.

In [18]:
scores_l, scores_svm, scores_svm

([0.9232053422370617, 0.9415692821368948, 0.9148580968280468],
 [0.9666110183639399, 0.9816360601001669, 0.9549248747913188],
 [0.9666110183639399, 0.9816360601001669, 0.9549248747913188])

In [19]:
from sklearn.model_selection import cross_val_score


`cross_val_score` is a function in the `sklearn.model_selection` module that provides a simple way to perform cross-validation and obtain scores for a given model and dataset. It takes as input a machine learning model, a dataset (features and target), and the number of folds to use for cross-validation. It then splits the dataset into the specified number of folds, trains the model on each fold while using the remaining folds as validation data, and returns the evaluation score for each fold.

The main advantage of using cross_val_score is that it simplifies the process of cross-validation, making it easier to compare the performance of different models or hyperparameters. Additionally, it provides an efficient way to obtain a reliable estimate of the model's performance on unseen data, by testing the model on multiple different test sets.

The function returns an array of scores (one for each fold) which can be used to calculate the mean and standard deviation of the performance of the model across all the folds.

**Logistic Regression**

In [23]:
Logistic_scores = cross_val_score(LogisticRegression(), digits.data, digits.target)
Logistic_scores

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _che

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [24]:
np.average(Logistic_scores)

0.9137650882079852

**Support Vector Machines (SVM)**

In [25]:
SVM_scores = cross_val_score(SVC(), digits.data, digits.target)
SVM_scores

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [27]:
np.average(SVM_scores)

0.9632838130609718

**Random** **Forest**

In [26]:
RFC_scores = cross_val_score(RandomForestClassifier(), digits.data, digits.target)
RFC_scores

array([0.93611111, 0.90833333, 0.95543175, 0.97214485, 0.9275766 ])

In [28]:
np.average(RFC_scores)

0.9399195295574125

**Best Performing is SVM with : 0.9632838130609718**